#!/usr/bin/env php
<?php
/*
dati due valori, rirona la percentule che il secondo valore rappresenta del primo
*/

// dato $totale e $perc, ritorna float valore
function get_perc($totale, $perc ){
    $decimal = 2;
    $x = $totale / 100 * $perc;
    $x = (float) round( $x, $decimal );
    return $x;
}
if( isset($argv[1]) && isset($argv[2]) && is_numeric($argv[1]) && is_numeric($argv[2]) ) {
    $totale   = $argv[1];
    $parziale = $argv[2];
    echo get_perc($totale, $parziale)."\n";
} else {
    die("specificare 2 valori: totale perc% = subtotale \n");
}