#!/usr/bin/env php
<?php
/*
dati due valori, rirona la percentule che il secondo valore rappresenta del primo
*/

// dato $totale e $parziale, ritorna intero 0-100 rappresentante la percentuale
function get_perc($totale, $parziale, $decimal=2){
    $x = 100 / ($totale/$parziale);
    $x = (float) round( $x, $decimal );
    return $x;
}
if( isset($argv[1]) && isset($argv[2]) && is_numeric($argv[1]) && is_numeric($argv[2]) ) {
    $totale   = $argv[1];
    $parziale = $argv[2];
    echo get_perc($totale, $parziale)."% \n";
} else {
    die("specificare 2 valori: totale subtotale = perc% \n");
}
